#!/bin/bash
echo "Enter first number: "
read num1
echo "Enter second number: "
read num2
add=$(($num1 + $num2))
echo "Addition result: $add"
subtract=$(($num1 - $num2))
echo "Subtraction result: $subtract"
multiply=$(($num1 * $num2))
echo "Multiplication result: $multiply"
if [ $num2 -ne 0 ]; then
divide=$(($num1 / $num2))
echo "Division result: $divide"
else
echo "Division by zero is not allowed"
fi
