#!/bin/bash
echo "Enter total marks: "
read total_marks
echo "Enter obtained marks: "
read obtained_marks
percentage=$(echo "scale=2; ($obtained_marks / $total_marks) * 100" | bc)
if (( $(echo "$percentage >= 90" | bc -l) )); then
 grade="A+"
elif (( $(echo "$percentage >= 80" | bc -l) )); then
 grade="A"
elif (( $(echo "$percentage >= 70" | bc -l) )); then
 grade="B"
elif (( $(echo "$percentage >= 60" | bc -l) )); then
 grade="C"
else
 grade="D"
fi
echo "Percentage: $percentage%"
echo "Grade: $grade"
